import { ArrowUpRight, Check, LockKeyhole, ShieldCheck, Trophy, X } from 'lucide-react'
import { NFT_TIERS } from '../../Services/freedomPlus'
const IMAGES={1:'/images/freedom-nft/tier-foundational.png',2:'/images/freedom-nft/tier-intermediate.png',3:'/images/freedom-nft/tier-advanced.png'}

export function FreedomNftMembership({membership,formatToken,nftForm,setNftForm,unlockForm,setUnlockForm,busy,submitMembership,unlockQualification,restoreEligibility}){
 const current=NFT_TIERS.find(x=>x.tier===membership.tier)
 return <div className="fn-page">
  <section className="fn-page-hero"><img src="/images/freedom-nft/membership-hero.png" alt="A premium membership card entering a secure digital vault"/><div className="fn-page-hero__shade"/><div className="fn-page-hero__copy"><span>Token-backed membership</span><h1>Build your Freedom NFT status</h1><p>Lock the exact qualifying balance for one active tier. Your tokens remain yours while they support membership.</p><div className="fn-page-hero__facts"><b>{current?.name||'No active NFT'}</b><em className={membership.rewardEligible?'eligible':''}>{membership.rewardEligible?'Reward eligible':'Not eligible'}</em></div></div></section>
  <section className="fn-surface fn-membership-status"><ShieldCheck/><div><span>Current membership</span><h2>{current?.name||'Choose your membership'}</h2><p>{membership.tier?formatToken(membership.lockedFGT)+' FGT + '+formatToken(membership.lockedFPT)+' FPT locked':'Select a tier and commit its exact qualifying token total.'}</p></div><strong className={membership.rewardEligible?'eligible':''}>{membership.rewardEligible?'Active':'Qualification required'}</strong></section>
  <section className="fn-section"><header><span>Membership stages</span><h2>Select one qualifying tier</h2><p>FGT and FPT may be combined. Only available, uncommitted balances can be locked.</p></header><div className="fn-tier-selector">{NFT_TIERS.map(item=><button type="button" className={Number(nftForm.tier)===item.tier?'selected':''} key={item.tier} onClick={()=>setNftForm({tier:item.tier,fgt:'0',fpt:String(item.threshold)})}><img src={IMAGES[item.tier]} alt={item.name+' Freedom NFT membership'}/><span>Tier {item.tier}</span><h3>{item.name}</h3><strong>{item.threshold.toLocaleString()} tokens</strong><small>{item.poolShare}% monthly tier allocation</small>{membership.tier===item.tier&&<em><Check/> Current tier</em>}</button>)}</div></section>
  <section className="fn-surface fn-tool"><div><span>Qualifying commitment</span><h2>{membership.tier?'Update membership':'Mint membership'}</h2><p>Your entries must total the selected tier threshold exactly.</p></div><div className="fn-form"><label>FGT commitment<input type="number" min="0" value={nftForm.fgt} onChange={e=>setNftForm(x=>({...x,fgt:e.target.value}))}/></label><label>FPT commitment<input type="number" min="0" value={nftForm.fpt} onChange={e=>setNftForm(x=>({...x,fpt:e.target.value}))}/></label><button type="button" onClick={submitMembership} disabled={Boolean(busy)}><LockKeyhole/>{busy==='membership'?'Processing...':membership.tier?'Update membership':'Mint membership'}</button></div></section>
  {membership.tier>0&&<section className="fn-surface fn-tool"><div><span>Qualification controls</span><h2>{membership.rewardEligible?'Unlock qualifying tokens':'Restore reward eligibility'}</h2><p>{membership.rewardEligible?'Unlocking recalculates eligibility immediately.':'Restore the exact missing qualifying amount.'}</p></div><div className="fn-form"><label>FGT amount<input type="number" min="0" value={unlockForm.fgt} onChange={e=>setUnlockForm(x=>({...x,fgt:e.target.value}))}/></label><label>FPT amount<input type="number" min="0" value={unlockForm.fpt} onChange={e=>setUnlockForm(x=>({...x,fpt:e.target.value}))}/></label><button type="button" disabled={Boolean(busy)} onClick={membership.rewardEligible?unlockQualification:restoreEligibility}>{busy==='unlock'||busy==='restore'?'Processing...':membership.rewardEligible?'Unlock tokens':'Restore eligibility'}</button></div></section>}
 </div>
}

export function FreedomNftRewards({membership,rewardPeriods,formatToken,busy,claimReward}){
 const current=NFT_TIERS.find(x=>x.tier===membership.tier)
 return <div className="fn-page">
  <section className="fn-page-hero"><img src="/images/freedom-nft/rewards-hero.png" alt="A Freedom NFT card receiving digital rewards"/><div className="fn-page-hero__shade"/><div className="fn-page-hero__copy"><span>Monthly distribution</span><h1>Freedom NFT rewards</h1><p>Each published period uses one cutoff snapshot. Eligible members participate through their highest active tier.</p><div className="fn-page-hero__facts"><b>{current?.name||'No active tier'}</b><em className={membership.rewardEligible?'eligible':''}>{membership.rewardEligible?'Snapshot ready':'Not currently eligible'}</em></div></div></section>
  <section className="fn-section"><header><span>Pool structure</span><h2>Transparent allocation by membership tier</h2></header><div className="fn-allocation">{NFT_TIERS.map(t=><article key={t.tier}><img src={IMAGES[t.tier]} alt=""/><div><span>{t.name}</span><strong>{t.poolShare}%</strong><small>Tier {t.tier} allocation</small></div></article>)}</div></section>
  <section className="fn-section"><header><span>Reward history</span><h2>Published periods and claims</h2><p>Eligibility is fixed at each cutoff. Finalized entitlements remain claimable.</p></header><div className="fn-reward-periods">{rewardPeriods.length?rewardPeriods.map(p=><article key={p.periodId}><div className="fn-reward-periods__icon"><Trophy/></div><div><span>{p.periodId}</span><strong>{p.proof?.eligible?formatToken(p.reward)+' USDT':p.proof?.snapshotAvailable===false?'Proof archive unavailable':'Not eligible at cutoff'}</strong><small>{p.status==='published'?'Published on-chain':'Awaiting founder publication'}</small></div>{p.proof?.eligible&&p.status==='published'&&<button type="button" disabled={p.claimed||Boolean(busy)} onClick={()=>claimReward(p)}>{p.claimed?<><Check/> Claimed</>:<><ArrowUpRight/> Claim reward</>}</button>}</article>):<div className="fn-empty-rewards"><Trophy/><h3>No reward period is available yet</h3><p>Published monthly periods will appear here.</p></div>}</div></section>
 </div>
}

export function FreedomNftSuccessModal({success,onClose}){
 if(!success)return null
 return <div className="fn-success-backdrop" role="presentation" onMouseDown={e=>{if(e.target===e.currentTarget)onClose()}}><section className="fn-success-modal" role="dialog" aria-modal="true" aria-labelledby="fn-success-title"><button type="button" className="fn-success-modal__close" onClick={onClose} aria-label="Close"><X/></button><img src="/images/freedom-nft/success-achievement.png" alt="Achievement confirmed"/><span>Confirmed on-chain</span><h2 id="fn-success-title">{success.title}</h2><p>{success.message}</p>{success.hash&&<small>{success.hash.slice(0,10)}...{success.hash.slice(-8)}</small>}<button type="button" className="fn-success-modal__done" onClick={onClose}>Done</button></section></div>
}
