import { ArrowRight, Check, Flame, LockKeyhole, ShieldCheck, Trophy, WalletCards } from 'lucide-react'
import { NFT_TIERS } from '../../Services/freedomPlus'
const IMAGES={1:'/images/freedom-nft/tier-foundational.png',2:'/images/freedom-nft/tier-intermediate.png',3:'/images/freedom-nft/tier-advanced.png'}
const PRINCIPLES=[{icon:LockKeyhole,title:'Tokens stay locked',text:'Committed FGT and FPT remain yours while supporting membership.'},{icon:ShieldCheck,title:'One active tier',text:'Your highest active membership is the only tier included in each allocation.'},{icon:Flame,title:'Immediate qualification',text:'Eligibility follows the qualifying value maintained for your tier.'},{icon:Trophy,title:'Verifiable rewards',text:'Monthly eligibility and proofs remain tied to the published on-chain period.'}]
export default function FreedomNftOverview({membership,formatToken,openView}){
 const current=NFT_TIERS.find(t=>t.tier===membership.tier)
 return <div className="fn-page fn-overview">
  <section className="fn-overview-hero"><picture><source media="(max-width: 680px)" srcSet="/images/freedom-nft/overview-hero-mobile.png"/><img src="/images/freedom-nft/overview-hero-desktop.png" alt="Three premium Freedom NFT membership cards"/></picture><div className="fn-page-hero__shade"/><div className="fn-page-hero__copy"><span>Membership, recognition and long-term value</span><h1>Freedom NFT</h1><p>Turn qualifying FGT and FPT into a transparent membership status connected to monthly ecosystem rewards.</p><div className="fn-hero-actions"><button type="button" onClick={()=>openView('membership')}>Manage membership <ArrowRight/></button><button type="button" className="secondary" onClick={()=>openView('rewards')}>View rewards</button></div><div className="fn-page-hero__facts"><WalletCards/><b>{current?.name||'Not minted'}</b><em className={membership.rewardEligible?'eligible':''}>{membership.rewardEligible?'Reward eligible':'Not eligible'}</em></div></div></section>
  <section className="fn-section"><header><span>Three membership stages</span><h2>Choose the tier your qualifying balance supports</h2><p>FGT and FPT may be combined. Only available, uncommitted balances can be locked.</p></header><div className="fn-overview-tiers">{NFT_TIERS.map(t=><article key={t.tier} className={membership.tier===t.tier?'current':''}><img src={IMAGES[t.tier]} alt={t.name+' Freedom NFT tier'}/><div><span>Tier {t.tier}</span>{membership.tier===t.tier&&<em><Check/> Active</em>}<h3>{t.name}</h3><strong>{t.threshold.toLocaleString()} tokens</strong><small>FGT and/or FPT required</small><p><span>Monthly pool allocation</span><b>{t.poolShare}%</b></p></div></article>)}</div></section>
  <section className="fn-section"><header><span>Membership safeguards</span><h2>One status, one qualifying balance, one reward tier</h2></header><div className="fn-principles">{PRINCIPLES.map(({icon:Icon,title,text})=><article key={title}><Icon/><div><h3>{title}</h3><p>{text}</p></div></article>)}</div></section>
  <section className="fn-surface fn-journey"><div><span>Membership journey</span><h2>Lock, qualify, participate, and adjust</h2></div><ol><li><b>01</b><span>Lock the exact qualifying token combination.</span></li><li><b>02</b><span>Mint one wallet-bound active membership.</span></li><li><b>03</b><span>Enter eligible monthly snapshots.</span></li><li><b>04</b><span>Upgrade, restore, or downgrade when needed.</span></li></ol>{membership.tier>0&&<p>Currently locked: <strong>{formatToken(membership.lockedFGT)} FGT</strong> and <strong>{formatToken(membership.lockedFPT)} FPT</strong></p>}</section>
 </div>
}
